gazebo_client:
  joint_velocity_controller:
    joint_names:
      - front_left_hip_yaw
      - front_left_hip_pitch
      - front_left_knee_joint     
      - front_right_hip_yaw
      - front_right_hip_pitch
      - front_right_knee_joint    
      - rear_left_hip_yaw
      - rear_left_hip_pitch
      - rear_left_knee_joint      
      - rear_right_hip_yaw
      - rear_right_hip_pitch
      - rear_right_knee_joint     
    p_gains: [
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ]