gazebo_client:
  joint_names:
    - front_left_hip_yaw
    - front_left_hip_pitch
    - front_left_knee_joint     
    - front_right_hip_yaw
    - front_right_hip_pitch
    - front_right_knee_joint    
    - rear_left_hip_yaw
    - rear_left_hip_pitch
    - rear_left_knee_joint      
    - rear_right_hip_yaw
    - rear_right_hip_pitch
    - rear_right_knee_joint     

  joint_config: [
    75, 40, 40, -75, -40, -40, 120, -40, -40, -120, 40, 40 
  ]

  joint_velocity_controller:
    p_gains: [
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ]
    i_gains: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
    d_gains: [
      0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1
    ]
  joint_position_controller:
    p_gains: [
      1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000
    ]
    i_gains: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
    d_gains: [
      10,10,10,10,10,10,10,10,10,10,10,10
    ]
