joint_velocity_controller:
  type: tetrapod_gazebo/JointVelocityController
  id: tetrapod
  joint_names:
    -front_left_hip_yaw_joint  
    -front_left_hip_pitch_joint
    -front_left_knee_joint     
    -front_left_foot_joint     
    -front_right_hip_yaw_joint 
    -front_right_hip_pitch_join
    -front_right_knee_joint    
    -front_right_foot_joint    
    -rear_left_hip_yaw_joint   
    -rear_left_hip_pitch_joint 
    -rear_left_knee_joint      
    -rear_left_foot_joint      
    -rear_right_hip_yaw_joint  
    -rear_right_hip_pitch_joint
    -rear_right_knee_joint     
    -rear_right_foot_joint     
  gains: [
    1, 1, 1, 1, 1, 1, 1
  ]