gazebo_client:
  joint_names:
    - tetrapod::front_left_hip_yaw
    - tetrapod::front_left_hip_pitch
    - tetrapod::front_left_knee_joint     
    - tetrapod::front_right_hip_yaw
    - tetrapod::front_right_hip_pitch
    - tetrapod::front_right_knee_joint    
    - tetrapod::rear_left_hip_yaw
    - tetrapod::rear_left_hip_pitch
    - tetrapod::rear_left_knee_joint      
    - tetrapod::rear_right_hip_yaw
    - tetrapod::rear_right_hip_pitch
    - tetrapod::rear_right_knee_joint     

  joint_config: [
    #0, 0, 90, 0, 0, -90, 0, 0, -90, 0, 0, 90 
    #45, 0, 90, -45, 0, -90, 135, 0, -90, -135, 0, 90 
    45, -20, 90, -45, 20, -90, 135, 20, -90, -135, -20, 90 
  ]

  joint_velocity_controller:
    p_gains: [
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
    ]
    i_gains: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
    d_gains: [
      0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1
    ]
  joint_position_controller:
    p_gains: [
      500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500
    ]
    i_gains: [
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    ]
    d_gains: [
      5,5,5,5,5,5,5,5,5,5,5,5
    ]
